name: Sync CV to OneDrive

on:
  push:
    branches:
      - main  # Runs only on push to main branch
    paths:
      - 'dist/Jaeho_Cho_CV.pdf'  # Runs only if this file is modified

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONFIG }}' > ~/.config/rclone/rclone.conf

      - name: Sync CV to OneDrive
        run: |
          rclone copy dist/Jaeho_Cho_CV.pdf "Cooper Union OneDrive:" --progress
